# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. I will try and get back to you as soon as possible.

  Regards @fgl27

pullRequestOpened: >
  Thank your for raising your pull request. I will review it as soon as possible.

  Regards @fgl27
